name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Zephyr export
        run: west zephyr-export

      - name: Build Corneish Zen v2 Left
        run: west build -s zmk/app -b corneish_zen_v2_left -d build/left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Build Corneish Zen v2 Right
        run: west build -s zmk/app -b corneish_zen_v2_right -d build/right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/left/zephyr/zmk.uf2
            build/right/zephyr/zmk.uf2

      - name: Rename firmware files
        run: |
          cp build/left/zephyr/zmk.uf2 corneish_zen_v2_left.uf2
          cp build/right/zephyr/zmk.uf2 corneish_zen_v2_right.uf2

      - name: Upload left firmware
        uses: actions/upload-artifact@v4
        with:
          name: corneish_zen_v2_left
          path: corneish_zen_v2_left.uf2

      - name: Upload right firmware
        uses: actions/upload-artifact@v4
        with:
          name: corneish_zen_v2_right
          path: corneish_zen_v2_right.uf2